########################################
# プラグイン管理
########################################
[[plugins]]
repo = 'Shougo/dein.vim'

# スニペット 
[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugin]]
repo = 'Shougo/neosnippet-snippets'

# 非同期ジョブの互換ライブラリ(vim-lspの依存で必要)
[[plugins]]
repo = 'prabirshrestha/async.vim'

# 補完
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

# asyncompleteのソースにlspを追加
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

# asyncompleteのソースにfileを追加
[[plugins]]
repo = 'prabirshrestha/asyncomplete-file.vim'

# LSP
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
  source $HOME/dotfiles/vim/plugins/vim-lsp.vim
'''

# vim-lspの自動設定
[[plugins]]
repo = 'mattn/vim-lsp-settings'
#merged = 0
#hook_add = '''
#    source $HOME/vim/plugins/vim-lsp-settings.vim
#'''

# NERDTree
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  source $HOME/dotfiles/vim/plugins/nerdtree.vim
'''
