[[plugins]]
repo = 'Shougo/dein.vim'

#NERDTree
[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
  source ~/dotfiles/nvim/plugins/nerdtree.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  source ~/dotfiles/nvim/plugins/vim-airline.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
  source ~/dotfiles/nvim/plugins/vim-lsp.vim
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

